INSERT INTO STUDENT(ID, NAME, SURNAME, MAIL) VALUES
(1,'GINO','PILOTINO','gino.pilotino@mail.com'),
(2,'VLADIMIRO','PUTINO','vladimiro.putino@mail.com'),
(3,'STAN','LAUREL','stan.laurel@mail.com');

INSERT INTO COURSE(ID, COURSENAME, DESCRIPTION, CFU) VALUES
(1, 'INGEGNERIA AEROSPAZIALE', 'COME FAR VOLARE UN AEREO', 10),
(2, 'RELAZIONI INTERNAZIONALI', 'INVADERE LA RUSSIA NON È UNA BUONA IDEA', 8),
(3, 'TEATRO E CINEMA', 'COME FAR RIDERE SENZA PARLARE', 8);

INSERT INTO STUDENT_COURSE(STUDENT_ID, COURSE_ID) VALUES
(1,1),
(1,2),
(2,1),
(2,3),
(3,3);

--INSERT INTO COURSE_STUDENT(COURSE_ID, STUDENT_ID) VALUES
--(1,1),
--(2,1),
--(1,2),
--(3,2),
--(3,3);
